# docker build -t pet-care-app .
# docker run -p 5000:5000 pet-care-app

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 for the Flask app
EXPOSE 5000

# Define environment variable to indicate production mode
ENV FLASK_ENV=production

# Run app.py when the container launches
CMD ["python", "app.py"]
